//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ActiveTile.h
//  @ Date : 5/20/2013
//  @ Author : 
//
//


#ifndef _ACTIVETILE_H
#define _ACTIVETILE_H

enum coordinate{x, y, _x, _y};

class ActiveTile
{
public:
    
	ActiveTile(int ActiveLabels, int InactiveLabels, int ActivationSigmals, int TransmissionSignals);
	~ActiveTile();
	int TileID;
    int ActiveLabels;
    int InactiveLabels;
    int ActivationSignals;
    int TranmissionSignals;
    int X_YCoordinates;
    int Neighbors;
    void ModifyCoordinates();
    void ModifyNeighbors();
    void ModifyActiveLabels();
    void ModifyInactiveLabels();
    void ModifyActivetionSignals();
    void ModifyTransmissionSignals();
    void RotateTile();
    void MoveTile();
};

#endif  //_ACTIVETILE_H
