//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AssemblyTileSetManager.h
//  @ Date : 5/20/2013
//  @ Author : 
//
//


#ifndef _ASSEMBLYTILESETMANAGER_H
#define _ASSEMBLYTILESETMANAGER_H

class SetOfAssemblyTiles;

class AssemblyTileSetManager
{
public:
	AssemblyTileSetManager();
	AssemblyTileSetManager(SetOfAssemblyTiles S);
	~AssemblyTileSetManager();
    int ListOfReferencesToAssemblyTileSets;
    int NumberOfSets;
    void AccessAssemblyTileSet();
    void CreateANewSet();
    void GetAssemblyTileSetIterator();
    void DeleteSet();
    void StoreSetOnHardrive();
    void LoadSetFromHardrive();
};

#endif  //_ASSEMBLYTILESETMANAGER_H
