//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SetOfAssemblyTiles.h
//  @ Date : 5/20/2013
//  @ Author : 
//
//


#ifndef _SETOFASSEMBLYTILES_H
#define _SETOFASSEMBLYTILES_H

class AssemblyTile;

class SetOfAssemblyTiles
{
public:
	SetOfAssemblyTiles();
	SetOfAssemblyTiles(AssemblyTile A);
	SetOfAssemblyTiles(AssemblyTile A [], int n);
	~SetOfAssemblyTiles();
    int CollectionOfAssemblyTiles;
    int NumberOfAssemblyTiles;
    int SetID_StepNumber;
    void AddAssemblyTile();
    void RemoveAssemblyTile();
    void CheckIfTileIsInTheSet();
    void AccessAssemblyTile();
    void GetIterator();
};

#endif  //_SETOFASSEMBLYTILES_H
