//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Simulator.h
//  @ Date : 5/20/2013
//  @ Author : 
//
//


#ifndef _SIMULATOR_H
#define _SIMULATOR_H


class Simulator
{
public:
    int StepCounter;
    int AssemblyTileSetManager;
    int StrengthMap;
    int ThetaParameter;
    int NumberOfSteps;
    int SetOfAssemblyTiles Iterator;
    int FirstAssemblyTile Iterator;
    int SecondAssemblyTile Iterator;
    void Constructor(int SetOfAssemblyTiles, int StrengthMap, int ThetaParameter, int NumberOfSteps);
    void Initialize();
    void StartSimulation();
private:
    void CreateNewSetOfAssemblyTiles();
    void SelectNextSetOfAssemblyTiles();
    void SelectFirstAssemblyTile();
    void SelectSecondAssemblyTile();
    void FindFittingSpots();
    void AttemptToCombine();
    void Done();
    void CheckXYOverlap();
    void CheckBondsStrength();
    void TileModificationFunction();
};

#endif  //_SIMULATOR_H
