//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ActiveTile.cpp
//  @ Date : 5/20/2013
//  @ Author : 
//
//


#include "ActiveTile.h"

void ActiveTile::Constructor(int ActiveLabels, int InactiveLabels, int ActivationSigmals, int TransmissionSignals)
{

}

void ActiveTile::ModifyCoordinates()
{

}

void ActiveTile::ModifyNeighbors()
{

}

void ActiveTile::ModifyActiveLabels()
{

}

void ActiveTile::ModifyInactiveLabels()
{

}

void ActiveTile::ModifyActivetionSignals()
{

}

void ActiveTile::ModifyTransmissionSignals()
{

}

void ActiveTile::RotateTile()
{

}

void ActiveTile::MoveTile()
{

}


