//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AssemblyTile.cpp
//  @ Date : 5/20/2013
//  @ Author : 
//
//


#include "AssemblyTile.h"

void AssemblyTile::ConstructFromTwoTiles()
{

}

void AssemblyTile::GetTileFromCoordinates()
{

}

void AssemblyTile::MoveAssemblyTile()
{

}

void AssemblyTile::RotateAssemblyTile()
{

}

