//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AssemblyTileSetManager.cpp
//  @ Date : 5/20/2013
//  @ Author : 
//
//


#include "AssemblyTileSetManager.h"

void AssemblyTileSetManager::AccessAssemblyTileSet()
{

}

void AssemblyTileSetManager::CreateANewSet()
{

}

void AssemblyTileSetManager::GetAssemblyTileSetIterator()
{

}

void AssemblyTileSetManager::DeleteSet()
{

}

void AssemblyTileSetManager::StoreSetOnHardrive()
{

}

void AssemblyTileSetManager::LoadSetFromHardrive()
{

}

