//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Simulator.cpp
//  @ Date : 5/20/2013
//  @ Author : 
//
//


#include "Simulator.h"

void Simulator::Constructor(int SetOfAssemblyTiles, int StrengthMap, int ThetaParameter, int NumberOfSteps)
{

}

void Simulator::Initialize()
{

}

void Simulator::StartSimulation()
{

}

void Simulator::CreateNewSetOfAssemblyTiles()
{

}

void Simulator::SelectNextSetOfAssemblyTiles()
{

}

void Simulator::SelectFirstAssemblyTile()
{

}

void Simulator::SelectSecondAssemblyTile()
{

}

void Simulator::FindFittingSpots()
{

}

void Simulator::AttemptToCombine()
{

}

void Simulator::Done()
{

}

void Simulator::CheckXYOverlap()
{

}

void Simulator::CheckBondsStrength()
{

}

void Simulator::TileModificationFunction()
{

}

